### ISSUE TITLE
Search does not support internationalization

### ISSUE THREAD

**Issue by alibaba-easyexcel** [zalando-incubator/hexo-theme-doc#167] opened 2019-10-16 09:01 UTC
Thank you very much for the code. It's very useful, but there's a little problem.
## Expected Behavior
https://alibaba-easyexcel.github.io/
When I search 'DEMO' it gets a lot of results.But when I search '简单' it don't work.
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - NodeJS Version: 10.16.3
  - NPM Version:6.9.0
  - OS:windows 10
  - Hexo Version:1.0.0-rc.1

**Comment by rbarilani** [comment] 2020-09-22 21:18
closing as duplicate of #177

**Closed by rbarilani** 2020-09-22 21:18 UTC
