### ISSUE TITLE
I want to use this theme in normal way 

### ISSUE THREAD

**Issue by dokinchan** [zalando-incubator/hexo-theme-doc#105] opened 2018-01-26 06:35 UTC
I like this theme so I want to use it, but it is kind of difficult to use in normal way like- install hexo and just add the sources in theme directory and set up the _config.yml - 

Of course, It is working in the quick start way but I want to understand more deeply and customize this theme. 

I tried some way to use in normal way
Installing via git doesn't work with this url 
(git clone git@github.com:zalando-incubator/hexo-theme-doc.git themes/doc)
but I was able to clone with your github url. and I failed use this theme as a 'theme'.

After with the quick start way, I added a theme in the themes folder and changed theme tested, 
hopefully it worked - only after remove the swagger files. 
is there any way to set the config using swagger or not ? 

Can you please explain more about this theme's directories and structure ? 

and I use Korean language but the search doesn't support it. 
How can I make it through?

also I wonder 
is there any command sentence instead of using (hexo new post "title" ) ?
and updating navigation file command?

and I tried the scss file update but faild,
so I tried to edit the css file directly but it doesn't updated... do you know why?

**Comment by rbarilani** [comment] 2018-01-26 09:38
Hi @dokinchan thanks for your feedback. There is a lot to  answer so I will try one by one.

> I like this theme so I want to use it, but it is kind of difficult to use in normal way like- install hexo and just add the sources in theme directory and set up the _config.yml - .... 

You are right this theme it's in someway atypical... we push users to use NPM to manage the theme and provide customization entry point that don't require touching theme sources. This is done because we want users being able to update to newer version(s) of the theme by using `npm`, not copy and paste or GIT. If we were using the normal Hexo approach and user modified is local version of the theme, it will be hard for her/him  to update to new releases.

> After with the quick start way, I added a theme in the themes folder and changed theme tested,
hopefully it worked - only after remove the swagger files.
is there any way to set the config using swagger or not ?

Can you open a specific issue describing this problem? With the steps to reproduce the problem, it will help us to keep track of this unexpected behaviour.

> Can you please explain more about this theme's directories and structure ?

I suggest you to know more about internals to have a look to the Development section in our README, but in any case the main differences between this theme and the "usual" blog themes are:

- css and js are precompiled (is not Hexo compiling them on runtime but we as maintainers prepare them) 
- the most interactive parts of the layout such as search, navigation, etc. are React components... so to update them the theme must be "re-compiled"
- the theme add also some hexo plugin for managing search, swagger, etc.
- the theme doesn't use "posts" but just "pages" 

> and I use Korean language but the search doesn't support it. How can I make it through?

Can you open a specific issue for that?

> also I wonder
is there any command sentence instead of using (hexo new post "title" ) ? and updating navigation file command?

No there isn't but we are open to suggestions how it should look like.

> and I tried the scss file update but faild,
so I tried to edit the css file directly but it doesn't updated... do you know why?

Yes is related to compilation, refer to the [development section](https://github.com/zalando-incubator/hexo-theme-doc#compile) to know how to recompile.

If you want to override style there is also another way. You can provide partials that will be included in the layout and there you can use `<link>` to include css files, extra js files. etc.... [check this out](https://zalando-incubator.github.io/hexo-theme-doc/usage-and-configuration/project-partials.html)

**Comment by rbarilani** [comment] 2018-03-14 10:50
@dokinchan Can I close this issue?

**Comment by rbarilani** [comment] 2018-03-27 08:49
Closing. @dokinchan Feel free to reopen-it.

**Closed by rbarilani** 2018-03-27 08:49 UTC
Labels: need-follow-up, question
